### ISSUE TITLE
unknown method rectangle at line 114 in TableExtractor.java

### ISSUE THREAD

**Issue by gandavarapudinakar** [rostrovsky/pdf-table#2]

**Comment by gandavarapudinakar** [comment]
i think we Should add Core.rectangle()

**Comment by gandavarapudinakar** [comment]
'and also getting error '
Exception in thread "main" java.lang.NoSuchMethodError: org.opencv.imgproc.Imgproc.boundingRect(Lorg/opencv/core/MatOfPoint;)Lorg/opencv/core/Rect;
	at pdftable.TableExtractor.getTableBoundingRectangles(TableExtractor.java:102)
	at pdftable.PdfTableReader.parsePdfTablePage(PdfTableReader.java:99)
	at pdftable.PdfTableReader.parsePdfTablePages(PdfTableReader.java:120)
	at pdftable.PdfTableReader.parsePdfTablePage(PdfTableReader.java:135)
	at pdftable.Test.main(Test.java:17)
